services:
## banco postgres
  postgres:
    container_name: postgres
    image: postgres:${PORTGRES_VERSION}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_bridge_net
 ## Kube news  
  kubenews:
    container_name: kubenews
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_PASSWORD : ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST : postgres
    networks:
      - kube_news_bridge_net
## volumes
volumes:
  postgres_docker_vol:
    name: compose_vol
## networks 
networks:
  kube_news_bridge_net : 
    driver: bridge
