services:
  postgres:
    container_name: postgres
    image: postgres:12.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_bridge_net
  kubenews:
    container_name: kubenews
    image: usantos802/kubenews:v1
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_PASSWORD : admin123
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      DB_HOST : postgres
    networks:
      - kube_news_bridge_net
volumes:
  postgres_docker_vol:
    name: compose_vol
networks:
  kube_news_bridge_net : 
    driver: bridge
